#!/usr/bin/env python3
"""Unified Gradient report renderer.

Usage:
    python render.py report.json --format pdf|pptx|both --out <base>

The validated report JSON remains the sole content source.  PDF output is
delegated unchanged to the sibling gradient_report.py renderer; PowerPoint
output is generated by the sibling gradient_pptx.py renderer.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path
from typing import Sequence

from gradient_pptx import RenderValidationError, load_report, render_report


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Render validated Gradient report JSON to PDF, PowerPoint, or both."
    )
    parser.add_argument("report", type=Path, help="validated report.json input")
    parser.add_argument(
        "--format",
        choices=("pdf", "pptx", "both"),
        default="pdf",
        dest="output_format",
        help="output format (default: pdf)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="output base path; .pdf or .pptx is added",
    )
    return parser


def _output_base(path: Path) -> Path:
    if path.suffix.lower() in {".pdf", ".pptx"}:
        return path.with_suffix("")
    return path


def _render_pdf(report_path: Path, output_path: Path) -> int:
    renderer = Path(__file__).with_name("gradient_report.py")
    if not renderer.is_file():
        print(f"ERROR — PDF renderer not found: {renderer}", file=sys.stderr)
        return 2
    output_path.parent.mkdir(parents=True, exist_ok=True)
    report = load_report(report_path)
    arguments = [sys.executable, str(renderer)]
    if report.get("slides") and not report.get("sections"):
        arguments.append("--deck")
    arguments.extend((str(report_path), str(output_path)))
    completed = subprocess.run(
        arguments,
        check=False,
    )
    return completed.returncode


def _render_pptx(report_path: Path, output_path: Path) -> int:
    try:
        report = load_report(report_path)
        render_report(report, output_path)
    except RenderValidationError as error:
        print(
            f"FAIL — PowerPoint render validation: {len(error.errors)} issue(s)",
            file=sys.stderr,
        )
        for issue in error.errors:
            print(f"  - {issue}", file=sys.stderr)
        return 3
    except RuntimeError as error:
        print(f"ERROR — {error}", file=sys.stderr)
        return 2
    print(f"Wrote {output_path}")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    report_path = args.report.resolve()
    base = _output_base(args.out.resolve())
    if not report_path.is_file():
        print(f"ERROR — report JSON not found: {report_path}", file=sys.stderr)
        return 2

    return_codes: list[int] = []
    if args.output_format in {"pdf", "both"}:
        return_codes.append(_render_pdf(report_path, Path(f"{base}.pdf")))
    if args.output_format in {"pptx", "both"}:
        return_codes.append(_render_pptx(report_path, Path(f"{base}.pptx")))
    return max(return_codes, default=0)


if __name__ == "__main__":
    raise SystemExit(main())

